services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file: .env
    environment:
      - PYTHONPATH=/app
      - CHROMA_HOST=chromadb
      - CHROMA_PORT=8000
    volumes:
      - ./backend/app:/app/app:ro  # 开发时热重载
    depends_on:
      - chromadb
    
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_BASE=http://localhost:8000

  # 向量数据库服务
  chromadb:
    image: chromadb/chroma:latest
    ports:
      - "8001:8000"  # 避免与backend端口冲突
    volumes:
      - chroma_data:/chroma/chroma
    environment:
      - CHROMA_SERVER_HOST=0.0.0.0
      - CHROMA_SERVER_HTTP_PORT=8000

volumes:
  chroma_data: 